### PR TITLE
Engine and motor controller

### PR DESCRIPTION
**Pull request by eloycoto**
This PR has two commits, one for the feature, and another one with the simple unit test. To be extended if the behaviour is desired.

### CODE REVIEW

**Comment by punkto** [comment]
Thanks @eloycoto !!

First of all. At the lowest level, yes, we use 2 GIPIOs configured as PWM outputs for driving the motors. We also use 2 extra GPIOs per motor to tell the hardware motor driver to drive the motor forward/backwards/do nothing

Regarding the specific pins, here are the references to 
- the robot schematics https://github.com/pcounhago/mightybuga-board/tree/master/v1.1
- the C code we have used in the past with the board is this https://github.com/hmightypirate/AllMyCircuits/blob/develop/src/mightybug_a/setup.c#L163 . The idea is to use the same registers configuration until new ideas came.

Regarding the concrete API for Engine, probably @eLeDe and/or @hmightypirate can give a better opinion than me.

**Comment by punkto** [comment]
Regarding the tests. They are more than welcome :D

Your proposal is make BSC's library unit tests that are compiled for the host/native architecture in ./test, isn't it? For me that is OK, but expect to have the less logic related code in the BSC. For example, I'm not sure if the Engine part of your code that should implement the differential drive should go in ./libs like the simple logger example. In the logger case, the tests are included in the crate, so we don't need extra folders at the root level. What do you think?

I would also like to make, at least for demonstration purposes, some unit tests for the BSC. Currently I am using the examples folder for manual tests, but I'm not happy with that. I know that are alternatives but I haven't start digging.

**Comment by eloycoto** [comment]
@punkto a lot of changes has been made to address your concerns :-)

**Comment by punkto** [comment]
Thanks @eloycoto , seems nice :D. I'll try to get some hardware with motors (o a logic analyzer at leasr) to test and merge it this week.

**Pull request merged**
